### ISSUE TITLE
Kubernetes ReplicationController vs Deployment

### ISSUE THREAD

**Issue by panzerdev** [grpc-ecosystem/grpc-simon-says#4]
I wonder why you use a ReplicationController instead of a Deployment for the Pod? I thought the RC is deprecated and the Deployment is now the right thing to do.

**Comment by markmandel** [comment]
I have the code to update this - I should also do a PR for it.

**Comment by thesandlord** [comment]
@markmandel any update on this? Should be a very straightforward change, I can do it if you want.

**Comment by markmandel** [comment]
I've got this tied up with the upgrade to gRPC 1.0 - which I have some infrastructure work I want to complete on gRPC before wrapping it all in together. So it's coming, I just haven't got there yet.

**Comment by markmandel** [comment]
This has now been merged, so I'm closing this ticket.
